name: cs486-assignment4

services:
  frontend:
    build: ./frontend/
    ports:
      - "5173:5173"
  backend:
    build: ./backend/
    ports:
      - "8800:8800"
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
