name: cs486-assignment4

services:
  frontend:
    build: ./frontend/
    ports:
      - "5173:5173"
  backend:
    build: ./backend/
    ports:
      - "8800:8800"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    command: --default-authentication-plugin mysql_native_password
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root
      timeout: 10s
      interval: 1s
      retries: 10
